### ISSUE TITLE
We are able to create a new company by selecting Paused sub-agents.(Agent Panel)

### ISSUE THREAD

**Issue by SwatiRani06** [pcspl92/webpanel#110]
**Description of the bug**
 If we select the Paused sub-agent and create new company then new company has created successfully.

**Steps to reproduce the behavior:**
1. Go to 'https://www.pulseptt.com/agent.html'
2. Login with valid credential:- 1. User name: john 2. Password: 12345678
3. Navigate to Company Management.
4. Select Create new company.
5. Click on Sub-agent drop- down Button.
6. Enter Account username:- Frik
7. Enter Password:- 12345678
8. Enter Confirm Password:- 12345678
9. Enter Company Name:- Frek communication
10. Enter contact number:- 3245678901
11. Select Sub-agent:-      (Paused sub-agent visible as blank in drop-down menu)
12. Click on Save button.
13. See error.

**Expected behavior**
We should not able to create a company by selecting Paused sub-agent. when we select a Paused sub-agent and create company then pop-up must come that selected sub-agent is Paused.
**Screenshots**
![BugFG](https://user-images.githubusercontent.com/102597212/163942272-ebed5065-d96d-47ac-98b5-013c1c178cb5.PNG)

In below screenshot  we can see the Created Company (s.no. 22)
![bugfrk 2](https://user-images.githubusercontent.com/102597212/163942375-5842b226-8283-484d-a9e9-be204235ba66.PNG)

**Desktop**
OS: Windows 10
Browser :Version 100.0.4896.60 (Official Build) (64-bit)
Version [0.1.1]

**Comment by pcspl92** [comment]
Expected : Paused sub agent  shouldn't  be  in the list while creating company

**Comment by SwatiRani06** [comment]
This bug hasn't  Resolved if we consider Expected behavior Provided by pcspl92.
