### ISSUE TITLE
We are able to create a New License by selecting Paused Company.(Agent Panel)

### ISSUE THREAD

**Issue by SwatiRani06** [pcspl92/webpanel#113]
**Description of  the bug**
We are able to create a new License order by selecting Paused Company.

**Steps to reproduce the behavior:**
1. Go to 'https://www.pulseptt.com/agent.html'
2. Login with valid credential:- 1. User name: john 2. Password: 12345678
3. Navigate to License Management.
4. Click on New License Order.
5. Select Company:- Dell Company(Paused)
6. Select License Type:- PTT user
7. Select License renewal type:- Monthly.
8. Enter Quantity:- 1
9. Check Features
10. Click on Purchase button
11. See error.

**Expected behavior**
Not Possible to create new license order under Paused Company. Pop-up must come that selected company is Paused.
**Screenshots**
![bug company](https://user-images.githubusercontent.com/102597212/163984193-07ba5d53-0ab4-44f1-b1ed-36bfec579cbc.PNG)

**Desktop (please complete the following information):**
 OS: Windows 10
Browser :Version 100.0.4896.60 (Official Build) (64-bit)
Version [0.1.1]

**Comment by useashu** [comment]
there is no such issue from my side
