### ISSUE TITLE
A fix autogenerated Receiving Port Address(Company Panel).

### ISSUE THREAD

**Issue by RanjitUpadhyay** [pcspl92/webpanel#12]
**Describe the bug**
 Receiving port address is not auto generated (Control Station  Account)  in Create Users.

**To Reproduce**
1.Enter in the address bar-pulseptt.com
2.Login With Id and Password.
UserName-titan
Password-123456789
3.Click On Create New 
4.Click On Select Account Type as 
Control Station ."

**Expected behavior**
"It must auto generated Receiving port address."

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Version 100.0.4896.60 (Official Build) (64-bit)
Version: [0.1.1]

**Comment by SaraswatGit** [comment]
This issue is working fine on my local machine. May I get some more details on the bug
![image](https://user-images.githubusercontent.com/58114914/160863917-44d39902-5724-4ece-a85f-26cd89c1daf4.png)

**Comment by ashishBhatnagar01** [comment]
This issue is working fine on my local machine too!
