### ISSUE TITLE
Text Alignment issue under Update License Order.(Agent Panel)

### ISSUE THREAD

**Issue by SwatiRani06** [pcspl92/webpanel#128]
**Description of the bug**
Text "All Accounts" and corresponding check box is not aligned Properly.

**Steps to reproduce the behavior:**
1. Go to 'https://www.pulseptt.com/agent.html'
2. Login with valid credential:- 1. User name: john 2. Password: 12345678
3. Navigate to License Management.
4. Click on Update License Order.
5. Select order:- 4
6. Select Update Type:- Renew.
7. See error.

**Expected behavior**
Proper Alignment of Label "All accounts" and "check box"

**Screenshots**
![bug](https://user-images.githubusercontent.com/102597212/165237624-b8b892f3-ce7a-4ac5-8ce7-6d127fb560bc.PNG)

**Desktop (please complete the following information):**
 OS: Windows 10
Browser :Version 100.0.4896.60 (Official Build) (64-bit)
Version [0.1.1]

**Comment by SwatiRani06** [comment]
This bug hasn't Resolved.
Current Alignment:-
![dev bug](https://user-images.githubusercontent.com/102597212/169954352-f83399f2-c8b2-4067-903c-260b0c695e94.PNG)
 Expected Alignment:-
![dev bug1](https://user-images.githubusercontent.com/102597212/169954403-b6209c4d-c233-4cef-9d75-fa808441dd0c.PNG)

**Comment by useashu** [comment]
There is no issue from my side. Can you please your code snippet of update
licence page.

**Comment by SwatiRani06** [comment]
Reopen:-
![bug5 4](https://user-images.githubusercontent.com/102597212/174590887-90dfe72c-35ad-4cb1-88b0-97de751d1157.PNG)
