### ISSUE TITLE
'Clear' Feature of Calendar under Login record is not working.(Agent Panel)

### ISSUE THREAD

**Issue by SwatiRani06** [pcspl92/webpanel#155]
**Description of  the bug**
 When we click on the 'Clear' Under Calendar then selected date not  clear, it remain filled with existing date.

**To Reproduce**
1. Go to 'https://www.pulseptt.com/agent.html'
2. Login with valid credential:- 1. User name: john 2. Password: 12345678
3. Navigate to Personal Center.
4. Click on Login Record.
5. Select From date 10.5.22
6. Click on Clear Button.
7. See error.

**Expected behavior**
After Clicking on "Clear" the selected date should turn into a Blank format:- dd-mm-yyyy.

**Screenshots**
![1652433536867](https://user-images.githubusercontent.com/102597212/168253120-8923af8b-0e23-476f-b077-ae52abcbd17a.JPEG)

**Desktop (please complete the following information):**
OS: Windows 10
Browser :Version 100.0.4896.60 (Official Build) (64-bit)
Version [0.2.1]

**Additional context**
Same issue on 'View user activity log' , 'View Order History' , 'Transaction' and 'View Users'  Page.

**Comment by SwatiRani06** [comment]
As I have mentioned in Additional context this issue is same on 'View user activity log' , 'View Order History' , 'Transaction' and 'View Users' Page. Now this issue has resolved from 'Login record' and 'view user activity log' Page. but still same on  'View Order History' , 'Transaction' and 'View Users' Page.

**Comment by useashu** [comment]
Issue resolved.

**Comment by SwatiRani06** [comment]
Issue Still Same on 'View Order History' and 'Transaction', 'View user account' Page.

**Comment by useashu** [comment]
i have pushed the code again it is resolved from my side
