### ISSUE TITLE
Wrong layout in 'Order List'.(Company)

### ISSUE THREAD

**Issue by RanjitUpadhyay** [pcspl92/webpanel#170]
**Describe the bug**
Wrong layout , spelling mistake(spelling of 'Type' is written as 'Tpye' ) in 'Order List' and no space between colon(:) and text in Order Transaction History.(See the attached fig.)

**To Reproduce**
1.Enter in the address bar-pulseptt.com
2.Login With Id and Password.
UserName-titan
Password-123456789
3.Click on "Order List"  and then  Order Transaction History.

**Expected behavior**
A proper alignment with correct layout must be present and spelling of 'Type' is written as 'Tpye' must be corrected.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Version 100.0.4896.60 (Official Build) (64-bit)
Version: [0.2.1.2]

 Order Transaction History-

![Capture149](https://user-images.githubusercontent.com/102597059/170962642-08cd4c91-91b9-4b0c-8e62-4eac1e7ab348.PNG)

Order List-

![Capture150](https://user-images.githubusercontent.com/102597059/170962732-1d670a69-49b2-4803-a552-09f5ec2087df.PNG)

**Comment by useashu** [comment]
please give a detail description of the issue.

**Comment by RanjitUpadhyay** [comment]
In order list , It is written 'S. No' like S.
                                                         No
