### ISSUE TITLE
Wrong Page layout of 'View User List'.(Company Panel)

### ISSUE THREAD

**Issue by RanjitUpadhyay** [pcspl92/webpanel#181]
**Describe the bug**
Wrong Page layout of 'View User List'. 'S.No' column is not visible.

**To Reproduce**
1.Enter in the address bar-pulseptt.com
2.Login With Id and Password.
UserName-ranjeet
Password-12345678
3.Click On 'View User List' and observe  'S.No' column is not visible.

**Expected behavior**
 'S.No' column must be visible.

**Desktop (please complete the following information):**
 OS: Windows 10
Browser: Version 100.0.4896.60 (Official Build) (64-bit)
Version: [0.2.5.1]

![Capture132](https://user-images.githubusercontent.com/102597059/170000305-39b2a3ca-1594-497a-86ba-12d6e9e9f575.PNG)

**Comment by useashu** [comment]
There is no issue from my side.

**Comment by RanjitUpadhyay** [comment]
In my Pc, I checked in Chrome and Edge , in both browsers the S.No. column is not visible. (attached screenshot is just snapped )

![Capture143](https://user-images.githubusercontent.com/102597059/170475925-952eb8be-fe30-4131-8c3d-9845b947b984.PNG)

**Comment by RanjitUpadhyay** [comment]
GO through UserName-ranjeet & Password-12345678 check



![Capture206](https://user-images.githubusercontent.com/102597059/174533229-7f3f6cca-1cfd-43de-b42d-02b080970f75.PNG)
