### ISSUE TITLE
 Result of To-date is  Not sorted under View User activity log, Login records and Transactions Page(Agent Panel)

### ISSUE THREAD

**Issue by SwatiRani06** [pcspl92/webpanel#21]
**Describe the bug**
When we Select To-date and From-date from the Calendar under View User activity log, Login records and Transactions Page then the data of Selected to-date is not visible in a Table of each Page.

**Steps to reproduce the behavior:**
1. Go to 'https://www.pulseptt.com/agent.html'
2. Login with valid credential:- 1' User name: john 2. Password: 12345678.
3.  Navigate to Personal Center.
4.  Select View User Activity Logs.
5. Select From-date:- 2.3.2022.
6. Select to-date:- 29.3.2022.
7. Click on Search Button.
8.  See error.

**Expected behavior**
The data of selected To-date must be sorted.

**Screenshots**
![bug 10](https://user-images.githubusercontent.com/102597212/160799230-a5172ff3-a639-401f-aa62-406de58d349b.PNG)

**Desktop**
  OS: Windows 10
  Browser :Version 100.0.4896.60 (Official Build) (64-bit)
  Version [0.1.1]

**Comment by SwatiRani06** [comment]
This Issue is not Completely Resolved. Same issue on "Transaction" Page still exist.
![trans bug](https://user-images.githubusercontent.com/102597212/169746050-fe436356-d33f-4ca6-9a66-680b92e7538d.PNG)

**Comment by SwatiRani06** [comment]
Build:-  0.2.5.1

**Comment by useashu** [comment]
Now issue resolved on all the pages.

**Comment by SwatiRani06** [comment]
Issue not Resolved.

**Comment by useashu** [comment]
I have pushed the modified code and it is working from my side.

**Comment by SwatiRani06** [comment]
This Bug has Resolved on View User activity log and Login records page but not on Transaction Page. Right now on Transaction Page 'Search button' is not working.

**Comment by useashu** [comment]
Please Check now it is working.
