### ISSUE TITLE
After Creating a new Company , creating a PTT User gives pop-up error of '{"user":"User with given username is already registered."}' in Create New User.(Company Panel)

### ISSUE THREAD

**Issue by RanjitUpadhyay** [pcspl92/webpanel#238]
**Describe the bug**
After Creating a new Company , creating a PTT User gives pop-up error of '{"user":"User with given username is already registered."}' in Create New User. While this is a new company creating first ptt user should not give any such error(possible reason is that I might created the ptt user with the same user name in another company ).

**To Reproduce**
1.Enter in the address bar-pulseptt.com
2.Login With Id and Password.
UserName-pulse123
Password-123456789
3.Click On 'Create User' and Create a PTT User.

**Expected behavior**
While this is a new company and for a  new company creating first ptt user should not give any such error.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Version 100.0.4896.60 (Official Build) (64-bit)
Version: [0.3.8]

![Capture191](https://user-images.githubusercontent.com/102597059/173510087-f4d5a5af-8d69-483e-b93b-4b1cbf35dd40.PNG)

**Comment by RanjitUpadhyay** [comment]
Creating a new ptt which was created in another company causing a server error.

**Comment by useashu** [comment]
pLease attach screen of the server error.

**Comment by RanjitUpadhyay** [comment]
when I am writing text field of Account Username and User Display Name same which was created in another company then it is causing error.


![Capture219](https://user-images.githubusercontent.com/102597059/174746707-22fb5453-57d3-4ef3-9ddd-e4923ab50a8b.PNG)
