### ISSUE TITLE
The PTT Users in 'Add PTT User Accounts' is showing wrong users which was not created is showing under Create New Contacts.(Company Panel)

### ISSUE THREAD

**Issue by RanjitUpadhyay** [pcspl92/webpanel#246]
**Describe the bug**
The PTT Users in 'Add PTT User Accounts' is showing wrong users(fake users) which was not created is showing under Create New Contacts. (one possible reason is that while creating new ptt user getting an error like **' pop-up error of '{"user":"User with given username is already registered."}'**  also counted as a ptt user and added in 'Add PTT User Accounts' under Create New Contacts )(see the screenshots)

**To Reproduce**
1.Enter in the address bar-pulseptt.com
2.Login With Id and Password.
UserName-tata
Password-12345678
3.Click On 'Create User' and Create a new PTT user and get an error like **' pop-up error of '{"user":"User with given username is already registered."}'** and create some ptt users without any error .
4.Now go to New Contact List and check the PTT Users number.

**Expected behavior**
 'Add PTT User Accounts' must show users which was created.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Version 100.0.4896.60 (Official Build) (64-bit)
Version: [0.3.8]

![Capture198](https://user-images.githubusercontent.com/102597059/173549469-556fc0a8-7f05-404b-b8d5-88ba8fd632ad.PNG)

**Comment by useashu** [comment]
Previously with some errors ptt users created now they will not create using any errors and hence no more fake ptt users can be shown in create contact list. But previous fake ptt users can be shown. To solve this you have to delete those fake users data from your database.
