### ISSUE TITLE
Incorrect Time show on Login Record Page.(Agent Panel)

### ISSUE THREAD

**Issue by SwatiRani06** [pcspl92/webpanel#256]
**Description of the bug**
Activities logged in time is not Correctly updated in table.

**To Reproduce**
**Steps to reproduce the behavior:**

1. Go to 'https://www.pulseptt.com/agent.html'
2. Login with valid credential:- 1. User name: john 2. Password: 12345678
3. Navigate to Personal center.
4. Click on Login Record.
5. See error.

**Expected behavior**
Correct Time Should Updated.

**Screenshots**
![log bug](https://user-images.githubusercontent.com/102597212/173803474-b2cec20d-82d3-4158-8668-7d2bae1954a9.PNG)

**Desktop (please complete the following information):**
OS: Windows 10
Browser :Version 100.0.4896.60 (Official Build) (64-bit)
Version [0.1.1]

**Comment by useashu** [comment]
Please explain the issue because there is no such issue. If you logout and login in same minute then it will show the same time. What is the issue?

**Comment by SwatiRani06** [comment]
![time bug](https://user-images.githubusercontent.com/102597212/173820421-4eb77d75-efb0-4e03-ac5e-cc69ce7e4a85.PNG)
 Just logged out and Logged in and current time is 17.19 but it is showing 11:49

**Comment by useashu** [comment]
It is showing correct time in my system. I recently pushed my code , Please pull and try and let me know.
