### ISSUE TITLE
After creating a 'Contact Number' with '+' sign from Create New User, It's '+' sign is not reflecting in  View User List.(Company Panel)

### ISSUE THREAD

**Issue by RanjitUpadhyay** [pcspl92/webpanel#320]
**Describe the bug**
After creating a 'Contact Number' with '+' sign from Create New User, It's '+' sign is not reflecting in  View User List.

**To Reproduce**
1.Enter in the address bar-pulseptt.com
2.Login With Id and Password.
UserName-tata
Password-12345678
3.Click On View User List.

**Expected behavior**
Contact Number' with '+' sign must be visible.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Version 100.0.4896.60 (Official Build) (64-bit)
Version: [0.4.8]

![Capture226](https://user-images.githubusercontent.com/102597059/176165231-d8d45fcf-14e5-4998-9d70-1e84d0627108.PNG)

**Comment by useashu** [comment]
will work now if you now modify or create new contacts. Previously it was not properly updated to the database.
