### ISSUE TITLE
Special characters of Contact no. not shown in Table. (Agent Panel)

### ISSUE THREAD

**Issue by SwatiRani06** [pcspl92/webpanel#321]
**Description of  the bug**
If we write contact number +1287678987654. then + is not shown in Table.

**To Reproduce**
1. Go to 'https://www.pulseptt.com/agent.html'
2. Login with valid credential:- 1. User name: john 2. Password: 12345678
3.  Navigate to Company management.
4.  Check on View Company List.

**Expected behavior**
       + sign should show in Table also.

**Screenshots**
![new buggg](https://user-images.githubusercontent.com/102597212/176166108-fcfc17f7-cfc0-4819-93f7-ba9063e600d5.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
- Browser :Version 100.0.4896.60 (Official Build) (64-bit)
- Version [0.1.1]

**Comment by useashu** [comment]
will work now if you now modify or create new contacts. Previously it was not properly updated to the database.

**Comment by SwatiRani06** [comment]
Special character should be optional. Now , if we entered Contact number 9876567898 then it is showing error but after entering +9876567898 it is accepted.
