### ISSUE TITLE
New Sub-agent Can Be created by using Space key(Agent Panel)

### ISSUE THREAD

**Issue by SwatiRani06** [pcspl92/webpanel#46]
**Description of the bug**
Under Create New sub-agent, we are able to Create Sub-agent by Clicking on Space Button.

**Steps to reproduce the behavior:**

1. Go to 'https://www.pulseptt.com/agent.html'
2. Login with valid credential:- 1. User name: john 2. Password: 12345678
3. Enter Account user name- (Space)
4. Enter Password:- (Space)
5. Enter Confirm password:- (Space)
6. Enter Sub-agent name:- (Space)
7. Enter Contact number :- 9876567894
8. Click on save Button.
10. Go to View Sub-agents.
11. See error.

**Expected behavior**
Sub-agent Shouldn't created by using only space key.
**Screenshots**
In Screenshot Sub-agent at S.no. 16 has created by using space key.
![bug22](https://user-images.githubusercontent.com/102597212/160988747-04db61b5-7237-43e8-8778-b4c48985967b.PNG)

**Desktop**
 OS: Windows 10
Browser :Version 100.0.4896.60 (Official Build) (64-bit)
Version [0.1.1]

**Comment by SwatiRani06** [comment]
This Bug is Still Same.

**Comment by SwatiRani06** [comment]
This Bug hasn't Resolved.

**Comment by useashu** [comment]
Please give the detail information what i need to do in this isssue.
