### ISSUE TITLE
Create New User for PTT(Company Panel)

### ISSUE THREAD

**Issue by RanjitUpadhyay** [pcspl92/webpanel#5]
**Describe the bug**
Save Button not functioning if we are not Selecting  TalkGroup, Default Talk Group, Assign Contact List , features  (not mandatory options) in Create New User. 

**To Reproduce**
1.Enter in the address bar-pulseptt.com
2.Login With Id and Password.
UserName-titan
Password-123456789
3.Click On Create New 
4.Select Account Type as PTT

**Expected behavior**
It must Save the newly Created User as TalkGroup, Default Talk Group, Assign Contact List, Features  are not mandatory options.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:Version 100.0.4896.60 (Official Build) (64-bit)
 - Version [0.1.7]

**Comment by RanjitUpadhyay** [comment]
![Capture43](https://user-images.githubusercontent.com/102597059/163924603-a9f530cc-fb10-4238-af10-7425f0275e44.PNG)
"Please select the order ID" error msg is displaying after Selecting the Order ID also.

**Comment by pcspl92** [comment]
Selecting talkgroup and Contact List is not a necessity  while creating a new user  ( Not a bug)

Though 
"Please select the order ID" error msg  is a bug

**Comment by RanjitUpadhyay** [comment]
If we are Selecting talkgroup and Contact List then save button is not functioning.
