### ISSUE TITLE
If we don't select  Sub-agent then it didn't show Error Message.(Agent Panel)

### ISSUE THREAD

**Issue by SwatiRani06** [pcspl92/webpanel#66]
**Description of  the bug**
If we don't select  Sub-agent from the drop-down menu under Create New Company  then it didn't show Error Message:- Please select sub-agent. And Save button Become freeze.

1. Go to 'https://www.pulseptt.com/agent.html'
2. Login with valid credential:- 1. User name: john 2. Password: 12345678.
3.  Account name:- Demarl Deo
4. Password:-123456789
5. Confirm Password:-123456789
6. Company Name:- infogain company
7. Contactnumber:- 2134568790
8. Click on save  button.
9. See error.

**Expected behavior**
It must show a Error Message:- Please Select Sub-agent.

**Screenshots**
![bug0999](https://user-images.githubusercontent.com/102597212/161515154-2abb6e22-b45e-4c36-a40a-9efaa5abaecf.PNG)

**Desktop** 
 OS: Windows 10
Browser :Version 100.0.4896.60 (Official Build) (64-bit)
Version [0.1.1]

**Comment by SwatiRani06** [comment]
This issue has not fixed.

**Comment by ashishBhatnagar01** [comment]
Do you have the latest code?

Please refer to the image.

![image](https://user-images.githubusercontent.com/63673042/162671857-8f034bcc-4320-42ea-8d1e-ef0cd65aec41.png)

**Comment by ashishBhatnagar01** [comment]
You have the latest updates on your local machine, right?

Also, please check the attached image.

![image](https://user-images.githubusercontent.com/63673042/162672076-7ac955c3-451e-4b6e-82c9-2d3603f4832c.png)

**Comment by SwatiRani06** [comment]
Okay..ya i don't have latest code. Will contact to Achal sir.
Thankyou

**Comment by pcspl92** [comment]
> You have the latest updates on your local machine, right?
> 
> Also, please check the attached image.
> 
> ![image](https://user-images.githubusercontent.com/63673042/162672076-7ac955c3-451e-4b6e-82c9-2d3603f4832c.png)

This issue has not been pushed to git .
Please Note - Only Commit when making a new version

**Comment by SwatiRani06** [comment]
This issue has not fixed.
