### ISSUE TITLE
Label issue under New License Order (UI, Agent Panel)

### ISSUE THREAD

**Issue by SwatiRani06** [pcspl92/webpanel#9]
**Description of the bug**
Instead of License Renewal there should be "License Renewal Type".

**Steps to reproduce the behavior:**
1. Go to 'https://www.pulseptt.com/agent.html'
2. Login with valid credential:- 1' User name; john 2. Password; 12345678
3. Navigate to License Management.

**Expected behavior**
Proper Labelling.

**Screenshots**
![bug0 5](https://user-images.githubusercontent.com/102597212/160772581-ab546d8e-c019-458b-9341-1149cd73aa7d.PNG)

**Desktop** 
    OS: Windows 10
    Browser :Version 100.0.4896.60 (Official Build) (64-bit)
    Version [0.1.1]

**Comment by ashishBhatnagar01** [comment]
What do you mean by proper labelling?

**Comment by SwatiRani06** [comment]
Instead of "License Renewal" there should be "License Renewal Type". As we see, when we click on Drop-down button then we get "Select License Renewal Type".

![1649997877863](https://user-images.githubusercontent.com/102597212/163519862-fe75d94d-a5e0-4896-9bbb-1110196ab91a.JPEG)

**Comment by ashishBhatnagar01** [comment]
Okay, I'll fix it,

Thanks for explaining!
